version = "2.0"

[settings]
default_environment = "dev"

# Common configuration for all environments
[common]
APP_NAME = "MyWebApp"
NODE_ENV = "development"
LOG_FORMAT = "json"
CORS_ORIGIN = "*"

# Local development
[environments.dev]
description = "Local development environment"
color = "green"
PORT = "3000"
HOST = "localhost"
DATABASE_URL = "postgres://dev:dev@localhost:5432/webapp_dev"
REDIS_URL = "redis://localhost:6379/0"
API_URL = "http://localhost:3000/api"
FRONTEND_URL = "http://localhost:8080"
AWS_REGION = "us-east-1"
AWS_S3_BUCKET = "webapp-dev-assets"
SMTP_HOST = "localhost"
SMTP_PORT = "1025"
DEBUG = "true"
LOG_LEVEL = "debug"

# Testing environment
[environments.test]
description = "Testing environment (for CI/CD)"
color = "cyan"
extends = "dev"
PORT = "3001"
DATABASE_URL = "postgres://test:test@localhost:5432/webapp_test"
REDIS_URL = "redis://localhost:6379/1"
LOG_LEVEL = "info"

# Production environment
[environments.prod]
description = "Production environment"
color = "red"
requires_confirmation = true
PORT = "8080"
HOST = "0.0.0.0"
NODE_ENV = "production"
DATABASE_URL = "postgres://produser:CHANGE_ME@db.prod.example.com:5432/webapp"
REDIS_URL = "redis://cache.prod.example.com:6379/0"
API_URL = "https://api.example.com"
FRONTEND_URL = "https://www.example.com"
AWS_REGION = "us-east-1"
AWS_S3_BUCKET = "webapp-prod-assets"
SMTP_HOST = "smtp.example.com"
SMTP_PORT = "587"
DEBUG = "false"
LOG_LEVEL = "warn"
CORS_ORIGIN = "https://www.example.com"
